swagger: '2.0'
info:
  title: Sharebox API
  description: API of the Sharebox server
  version: "1.0.0"
# the domain of the service
host: none
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /register:
    post:
      summary: Register to the sharebox server
      description: |
        Creates a user account on the sharebox server
      parameters:
        - name: user
          in: body
          description: user to register
          required: true
          schema: 
            $ref: '#/definitions/User'
      tags:
        - User
      responses:
        200:
          description: The user have been created
          schema:
            $ref: '#/definitions/User'
        400:
          description: Given parameters do not match the validation requirements
          schema:
            $ref: '#/definitions/Error'
        409:
          description: User already exists
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    properties:
      id:
        type: number
        format: long
        description: the user's id
      name:
        type: string
        description: the user's name
      login:
        type: string
        description: the user's login
      password:
        type: string
        description: the user's password
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
